services:
  - type: web
    name: linkinglink-server
    env: node
    plan: free
    branch: main
  buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: CORS_ORIGINS
        sync: false
